import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';

const centerSeed = [
  { id: 1, location: 'Gurugram', queue: 14, avg: 6, active: 2, total: 3, status: 'operational' },
  { id: 2, location: 'Pataudi', queue: 31, avg: 7, active: 2, total: 2, status: 'high' },
  { id: 3, location: 'Sohna', queue: 8, avg: 5, active: 1, total: 2, status: 'operational' },
];

const COPY = {
  en: { title:'KisanSlot Live Operations', subtitle:'Real-time mandi visibility after slot booking', token:'YOUR LIVE TOKEN', serving:'Now serving', ahead:'Farmers ahead', wait:'Estimated wait', min:'min', traffic:'Mandi traffic', low:'LOW LOAD', moderate:'MODERATE', high:'HIGH LOAD', trafficDesc:'Based on live queue and active counters.', arrival:'Smart arrival', leaveIn:n=>`Leave in about ${n} min`, leaveNow:'You can leave now', arrivalDesc:'Avoid reaching too early when the centre is delayed.', health:'Centre health', operational:'Operational', paused:'Paused', counters:(a,t)=>`${a}/${t} counters active`, model:'Queue model', perFarmer:n=>`${n} min/farmer`, modelDesc:'ETA recalculates as each token completes.', journey:'Procurement Journey', steps:['Slot Confirmed','Arrived at Centre','Live Queue','Quality Check','Weighing','Procurement Complete','Payment Initiated'], progress:'In progress', operator:'Operator Demo', operatorDesc:'Use these controls to demonstrate a live queue changing in front of judges.', next:'Call Next Farmer', breakdown:'Simulate Breakdown', resume:'Resume Centre', healthy:'Live system healthy. ETA updates when the queue advances.', pausedMsg:'Queue paused. Affected farmers would receive an SMS/app delay alert.', nearby:'Nearby Centre Load', nearbyDesc:'KisanSlot can recommend a less-crowded eligible centre instead of forcing a fixed queue.', balancing:'Dynamic Load Balancing', centre:'Centre', queue:'Queue', estWait:'Est. wait', status:'Status', action:'Action', suggest:'Suggest', procurementCentre:'Procurement Centre', dashboard:'Dashboard' },
  hi: { title:'किसानस्लॉट लाइव संचालन', subtitle:'स्लॉट बुकिंग के बाद मंडी की रीयल-टाइम स्थिति', token:'आपका लाइव टोकन', serving:'अभी सेवा जारी', ahead:'आगे किसान', wait:'अनुमानित प्रतीक्षा', min:'मिनट', traffic:'मंडी भीड़', low:'कम भीड़', moderate:'मध्यम', high:'अधिक भीड़', trafficDesc:'लाइव कतार और सक्रिय काउंटरों के आधार पर।', arrival:'स्मार्ट आगमन', leaveIn:n=>`लगभग ${n} मिनट बाद निकलें`, leaveNow:'आप अभी निकल सकते हैं', arrivalDesc:'केंद्र में देरी हो तो बहुत जल्दी पहुँचने से बचें।', health:'केंद्र स्थिति', operational:'चालू', paused:'रुका हुआ', counters:(a,t)=>`${a}/${t} काउंटर सक्रिय`, model:'कतार मॉडल', perFarmer:n=>`${n} मिनट/किसान`, modelDesc:'हर टोकन पूरा होने पर ETA दोबारा गणना होता है।', journey:'खरीद यात्रा', steps:['स्लॉट पक्का','केंद्र पर पहुँचे','लाइव कतार','गुणवत्ता जाँच','तौल','खरीद पूरी','भुगतान शुरू'], progress:'प्रगति में', operator:'ऑपरेटर डेमो', operatorDesc:'जजों के सामने लाइव कतार का बदलाव दिखाने के लिए इन नियंत्रणों का उपयोग करें।', next:'अगला किसान बुलाएँ', breakdown:'ब्रेकडाउन दिखाएँ', resume:'केंद्र फिर शुरू करें', healthy:'सिस्टम सामान्य है। कतार आगे बढ़ने पर ETA अपडेट होता है।', pausedMsg:'कतार रुकी है। प्रभावित किसानों को SMS/app देरी अलर्ट मिलेगा।', nearby:'नज़दीकी केंद्र भार', nearbyDesc:'किसानस्लॉट कम भीड़ वाले योग्य केंद्र का सुझाव दे सकता है।', balancing:'डायनेमिक लोड बैलेंसिंग', centre:'केंद्र', queue:'कतार', estWait:'अनुमानित प्रतीक्षा', status:'स्थिति', action:'कार्रवाई', suggest:'सुझाव', procurementCentre:'खरीद केंद्र', dashboard:'डैशबोर्ड' },
  pa: { title:'ਕਿਸਾਨਸਲੌਟ ਲਾਈਵ ਓਪਰੇਸ਼ਨ', subtitle:'ਸਲੌਟ ਬੁਕਿੰਗ ਤੋਂ ਬਾਅਦ ਮੰਡੀ ਦੀ ਰੀਅਲ-ਟਾਈਮ ਸਥਿਤੀ', token:'ਤੁਹਾਡਾ ਲਾਈਵ ਟੋਕਨ', serving:'ਹੁਣ ਸੇਵਾ ਜਾਰੀ', ahead:'ਅੱਗੇ ਕਿਸਾਨ', wait:'ਅੰਦਾਜ਼ਨ ਉਡੀਕ', min:'ਮਿੰਟ', traffic:'ਮੰਡੀ ਭੀੜ', low:'ਘੱਟ ਭੀੜ', moderate:'ਦਰਮਿਆਨੀ', high:'ਵੱਧ ਭੀੜ', trafficDesc:'ਲਾਈਵ ਕਤਾਰ ਅਤੇ ਚਾਲੂ ਕਾਊਂਟਰਾਂ ਦੇ ਆਧਾਰ ਤੇ।', arrival:'ਸਮਾਰਟ ਆਗਮਨ', leaveIn:n=>`ਲਗਭਗ ${n} ਮਿੰਟ ਬਾਅਦ ਨਿਕਲੋ`, leaveNow:'ਤੁਸੀਂ ਹੁਣ ਨਿਕਲ ਸਕਦੇ ਹੋ', arrivalDesc:'ਕੇਂਦਰ ਵਿੱਚ ਦੇਰੀ ਹੋਵੇ ਤਾਂ ਬਹੁਤ ਜਲਦੀ ਪਹੁੰਚਣ ਤੋਂ ਬਚੋ।', health:'ਕੇਂਦਰ ਦੀ ਸਥਿਤੀ', operational:'ਚਾਲੂ', paused:'ਰੁਕਿਆ ਹੋਇਆ', counters:(a,t)=>`${a}/${t} ਕਾਊਂਟਰ ਚਾਲੂ`, model:'ਕਤਾਰ ਮਾਡਲ', perFarmer:n=>`${n} ਮਿੰਟ/ਕਿਸਾਨ`, modelDesc:'ਹਰ ਟੋਕਨ ਪੂਰਾ ਹੋਣ ਤੇ ਅੰਦਾਜ਼ਨ ਸਮਾਂ ਮੁੜ ਗਿਣਿਆ ਜਾਂਦਾ ਹੈ।', journey:'ਖਰੀਦ ਯਾਤਰਾ', steps:['ਸਲੌਟ ਪੱਕਾ','ਕੇਂਦਰ ਤੇ ਪਹੁੰਚੇ','ਲਾਈਵ ਕਤਾਰ','ਗੁਣਵੱਤਾ ਜਾਂਚ','ਤੋਲ','ਖਰੀਦ ਪੂਰੀ','ਭੁਗਤਾਨ ਸ਼ੁਰੂ'], progress:'ਜਾਰੀ ਹੈ', operator:'ਓਪਰੇਟਰ ਡੈਮੋ', operatorDesc:'ਜੱਜਾਂ ਸਾਹਮਣੇ ਲਾਈਵ ਕਤਾਰ ਵਿੱਚ ਬਦਲਾਅ ਦਿਖਾਉਣ ਲਈ ਇਹ ਕੰਟਰੋਲ ਵਰਤੋ।', next:'ਅਗਲਾ ਕਿਸਾਨ ਬੁਲਾਓ', breakdown:'ਖਰਾਬੀ ਦਿਖਾਓ', resume:'ਕੇਂਦਰ ਮੁੜ ਚਾਲੂ ਕਰੋ', healthy:'ਸਿਸਟਮ ਠੀਕ ਚੱਲ ਰਿਹਾ ਹੈ। ਕਤਾਰ ਅੱਗੇ ਵਧਣ ਨਾਲ ਸਮਾਂ ਅਪਡੇਟ ਹੁੰਦਾ ਹੈ।', pausedMsg:'ਕਤਾਰ ਰੁਕੀ ਹੈ। ਪ੍ਰਭਾਵਿਤ ਕਿਸਾਨਾਂ ਨੂੰ SMS/app ਦੇਰੀ ਸੁਚੇਤਨਾ ਮਿਲੇਗੀ।', nearby:'ਨੇੜਲੇ ਕੇਂਦਰਾਂ ਦੀ ਭੀੜ', nearbyDesc:'ਕਿਸਾਨਸਲੌਟ ਘੱਟ ਭੀੜ ਵਾਲੇ ਯੋਗ ਕੇਂਦਰ ਦਾ ਸੁਝਾਅ ਦੇ ਸਕਦਾ ਹੈ।', balancing:'ਡਾਇਨਾਮਿਕ ਲੋਡ ਬੈਲੈਂਸਿੰਗ', centre:'ਕੇਂਦਰ', queue:'ਕਤਾਰ', estWait:'ਅੰਦਾਜ਼ਨ ਉਡੀਕ', status:'ਸਥਿਤੀ', action:'ਕਾਰਵਾਈ', suggest:'ਸੁਝਾਓ', procurementCentre:'ਖਰੀਦ ਕੇਂਦਰ', dashboard:'ਡੈਸ਼ਬੋਰਡ' },
  mr: { title:'किसानस्लॉट लाइव्ह ऑपरेशन्स', subtitle:'स्लॉट बुकिंगनंतर मंडीची रिअल-टाइम स्थिती', token:'तुमचा लाइव्ह टोकन', serving:'सध्या सेवा', ahead:'पुढे शेतकरी', wait:'अंदाजे प्रतीक्षा', min:'मिनिटे', traffic:'मंडी गर्दी', low:'कमी गर्दी', moderate:'मध्यम', high:'जास्त गर्दी', trafficDesc:'लाइव्ह रांग आणि सक्रिय काउंटरांवर आधारित.', arrival:'स्मार्ट आगमन', leaveIn:n=>`सुमारे ${n} मिनिटांनी निघा`, leaveNow:'तुम्ही आता निघू शकता', arrivalDesc:'केंद्र उशिरा चालत असल्यास खूप लवकर पोहोचू नका.', health:'केंद्र स्थिती', operational:'कार्यरत', paused:'थांबलेले', counters:(a,t)=>`${a}/${t} काउंटर सक्रिय`, model:'रांग मॉडेल', perFarmer:n=>`${n} मिनिटे/शेतकरी`, modelDesc:'प्रत्येक टोकन पूर्ण झाल्यावर ETA पुन्हा मोजला जातो.', journey:'खरेदी प्रवास', steps:['स्लॉट निश्चित','केंद्रावर आगमन','लाइव्ह रांग','गुणवत्ता तपासणी','वजन','खरेदी पूर्ण','पेमेंट सुरू'], progress:'प्रगतीत', operator:'ऑपरेटर डेमो', operatorDesc:'न्यायाधीशांसमोर लाइव्ह रांग बदलताना दाखवण्यासाठी हे नियंत्रण वापरा.', next:'पुढील शेतकऱ्याला बोलवा', breakdown:'बिघाड दाखवा', resume:'केंद्र पुन्हा सुरू करा', healthy:'सिस्टम व्यवस्थित चालू आहे. रांग पुढे गेल्यावर ETA अपडेट होतो.', pausedMsg:'रांग थांबली आहे. प्रभावित शेतकऱ्यांना SMS/app सूचना मिळेल.', nearby:'जवळच्या केंद्रांचा भार', nearbyDesc:'किसानस्लॉट कमी गर्दीचे पात्र केंद्र सुचवू शकते.', balancing:'डायनॅमिक लोड बॅलन्सिंग', centre:'केंद्र', queue:'रांग', estWait:'अंदाजे प्रतीक्षा', status:'स्थिती', action:'कृती', suggest:'सुचवा', procurementCentre:'खरेदी केंद्र', dashboard:'डॅशबोर्ड' },
  gu: { title:'કિસાનસ્લોટ લાઇવ ઓપરેશન્સ', subtitle:'સ્લોટ બુકિંગ પછી મંડીની રિયલ-ટાઇમ સ્થિતિ', token:'તમારો લાઇવ ટોકન', serving:'હમણાં સેવા', ahead:'આગળના ખેડૂત', wait:'અંદાજિત રાહ', min:'મિનિટ', traffic:'મંડી ભીડ', low:'ઓછી ભીડ', moderate:'મધ્યમ', high:'વધુ ભીડ', trafficDesc:'લાઇવ કતાર અને સક્રિય કાઉન્ટર પર આધારિત.', arrival:'સ્માર્ટ આગમન', leaveIn:n=>`લગભગ ${n} મિનિટ પછી નીકળો`, leaveNow:'તમે હવે નીકળી શકો છો', arrivalDesc:'કેન્દ્ર મોડું ચાલે તો બહુ વહેલા પહોંચવાનું ટાળો.', health:'કેન્દ્ર સ્થિતિ', operational:'ચાલુ', paused:'રોકાયેલ', counters:(a,t)=>`${a}/${t} કાઉન્ટર સક્રિય`, model:'કતાર મોડેલ', perFarmer:n=>`${n} મિનિટ/ખેડૂત`, modelDesc:'દરેક ટોકન પૂર્ણ થાય ત્યારે ETA ફરી ગણાય છે.', journey:'ખરીદી યાત્રા', steps:['સ્લોટ પુષ્ટિ','કેન્દ્ર પર આગમન','લાઇવ કતાર','ગુણવત્તા તપાસ','વજન','ખરીદી પૂર્ણ','ચુકવણી શરૂ'], progress:'ચાલુ છે', operator:'ઓપરેટર ડેમો', operatorDesc:'જજ સામે લાઇવ કતાર બદલાતી બતાવવા આ નિયંત્રણો વાપરો.', next:'આગળના ખેડૂતને બોલાવો', breakdown:'બ્રેકડાઉન બતાવો', resume:'કેન્દ્ર ફરી શરૂ કરો', healthy:'સિસ્ટમ સારી રીતે ચાલી રહ્યું છે. કતાર આગળ વધે ત્યારે ETA અપડેટ થાય છે.', pausedMsg:'કતાર રોકાઈ છે. અસરગ્રસ્ત ખેડૂતને SMS/app સૂચના મળશે.', nearby:'નજીકના કેન્દ્રનો ભાર', nearbyDesc:'કિસાનસ્લોટ ઓછી ભીડવાળું યોગ્ય કેન્દ્ર સૂચવી શકે છે.', balancing:'ડાયનેમિક લોડ બેલેન્સિંગ', centre:'કેન્દ્ર', queue:'કતાર', estWait:'અંદાજિત રાહ', status:'સ્થિતિ', action:'ક્રિયા', suggest:'સૂચવો', procurementCentre:'ખરીદી કેન્દ્ર', dashboard:'ડેશબોર્ડ' },
  bn: { title:'কিষানস্লট লাইভ অপারেশন', subtitle:'স্লট বুকিংয়ের পর মান্ডির রিয়েল-টাইম অবস্থা', token:'আপনার লাইভ টোকেন', serving:'এখন পরিষেবা চলছে', ahead:'সামনে কৃষক', wait:'আনুমানিক অপেক্ষা', min:'মিনিট', traffic:'মান্ডির ভিড়', low:'কম ভিড়', moderate:'মাঝারি', high:'বেশি ভিড়', trafficDesc:'লাইভ সারি ও সক্রিয় কাউন্টারের ভিত্তিতে।', arrival:'স্মার্ট আগমন', leaveIn:n=>`প্রায় ${n} মিনিট পরে বের হন`, leaveNow:'আপনি এখন বের হতে পারেন', arrivalDesc:'কেন্দ্রে দেরি হলে খুব তাড়াতাড়ি পৌঁছাবেন না।', health:'কেন্দ্রের অবস্থা', operational:'চালু', paused:'স্থগিত', counters:(a,t)=>`${a}/${t} কাউন্টার সক্রিয়`, model:'সারি মডেল', perFarmer:n=>`${n} মিনিট/কৃষক`, modelDesc:'প্রতিটি টোকেন শেষ হলে ETA পুনরায় গণনা হয়।', journey:'ক্রয় যাত্রা', steps:['স্লট নিশ্চিত','কেন্দ্রে পৌঁছেছেন','লাইভ সারি','মান পরীক্ষা','ওজন','ক্রয় সম্পূর্ণ','পেমেন্ট শুরু'], progress:'চলমান', operator:'অপারেটর ডেমো', operatorDesc:'বিচারকদের সামনে লাইভ সারির পরিবর্তন দেখাতে এই নিয়ন্ত্রণ ব্যবহার করুন।', next:'পরবর্তী কৃষককে ডাকুন', breakdown:'ব্রেকডাউন দেখান', resume:'কেন্দ্র পুনরায় চালু করুন', healthy:'সিস্টেম স্বাভাবিক। সারি এগোলে ETA আপডেট হয়।', pausedMsg:'সারি বন্ধ আছে। প্রভাবিত কৃষকরা SMS/app সতর্কতা পাবেন।', nearby:'নিকটবর্তী কেন্দ্রের চাপ', nearbyDesc:'কিষানস্লট কম ভিড়ের যোগ্য কেন্দ্র সুপারিশ করতে পারে।', balancing:'ডায়নামিক লোড ব্যালেন্সিং', centre:'কেন্দ্র', queue:'সারি', estWait:'আনুমানিক অপেক্ষা', status:'অবস্থা', action:'কর্ম', suggest:'সুপারিশ', procurementCentre:'ক্রয় কেন্দ্র', dashboard:'ড্যাশবোর্ড' },
  ta: { title:'கிசான்ஸ்லாட் நேரடி செயல்பாடுகள்', subtitle:'ஸ்லாட் முன்பதிவுக்குப் பிறகு மண்டியின் நேரடி நிலை', token:'உங்கள் நேரடி டோக்கன்', serving:'இப்போது சேவை', ahead:'முன்னால் உள்ள விவசாயிகள்', wait:'மதிப்பிடப்பட்ட காத்திருப்பு', min:'நிமிடம்', traffic:'மண்டி நெரிசல்', low:'குறைந்த நெரிசல்', moderate:'மிதமான', high:'அதிக நெரிசல்', trafficDesc:'நேரடி வரிசை மற்றும் செயலில் உள்ள கவுண்டர்களின் அடிப்படையில்.', arrival:'ஸ்மார்ட் வருகை', leaveIn:n=>`சுமார் ${n} நிமிடங்களில் புறப்படுங்கள்`, leaveNow:'நீங்கள் இப்போது புறப்படலாம்', arrivalDesc:'மையம் தாமதமாக இருந்தால் மிக விரைவாக வர வேண்டாம்.', health:'மைய நிலை', operational:'செயலில்', paused:'இடைநிறுத்தம்', counters:(a,t)=>`${a}/${t} கவுண்டர்கள் செயலில்`, model:'வரிசை மாதிரி', perFarmer:n=>`${n} நிமிடம்/விவசாயி`, modelDesc:'ஒவ்வொரு டோக்கனும் முடிந்தபின் ETA மீண்டும் கணக்கிடப்படும்.', journey:'கொள்முதல் பயணம்', steps:['ஸ்லாட் உறுதி','மையம் வந்தடைந்தார்','நேரடி வரிசை','தரச் சோதனை','எடை','கொள்முதல் முடிந்தது','பணம் தொடங்கியது'], progress:'நடப்பில்', operator:'ஆபரேட்டர் டெமோ', operatorDesc:'நீதிபதிகளுக்கு நேரடி வரிசை மாற்றத்தை காட்ட இந்த கட்டுப்பாடுகளை பயன்படுத்தவும்.', next:'அடுத்த விவசாயியை அழைக்கவும்', breakdown:'பழுதை காட்டவும்', resume:'மையத்தை மீண்டும் தொடங்கு', healthy:'அமைப்பு நன்றாக இயங்குகிறது. வரிசை நகரும்போது ETA புதுப்பிக்கப்படும்.', pausedMsg:'வரிசை நிறுத்தப்பட்டுள்ளது. பாதிக்கப்பட்ட விவசாயிகளுக்கு SMS/app எச்சரிக்கை அனுப்பப்படும்.', nearby:'அருகிலுள்ள மைய சுமை', nearbyDesc:'குறைந்த நெரிசலுள்ள தகுதியான மையத்தை கிசான்ஸ்லாட் பரிந்துரைக்கலாம்.', balancing:'டைனமிக் லோட் பேலன்சிங்', centre:'மையம்', queue:'வரிசை', estWait:'காத்திருப்பு', status:'நிலை', action:'செயல்', suggest:'பரிந்துரை', procurementCentre:'கொள்முதல் மையம்', dashboard:'டாஷ்போர்டு' },
  te: { title:'కిసాన్‌స్లాట్ లైవ్ ఆపరేషన్స్', subtitle:'స్లాట్ బుకింగ్ తర్వాత మార్కెట్ రియల్-టైమ్ స్థితి', token:'మీ లైవ్ టోకెన్', serving:'ఇప్పుడు సేవలో', ahead:'ముందున్న రైతులు', wait:'అంచనా వేచి సమయం', min:'నిమి', traffic:'మార్కెట్ రద్దీ', low:'తక్కువ రద్దీ', moderate:'మధ్యస్థ', high:'అధిక రద్దీ', trafficDesc:'లైవ్ క్యూ మరియు యాక్టివ్ కౌంటర్ల ఆధారంగా.', arrival:'స్మార్ట్ రాక', leaveIn:n=>`సుమారు ${n} నిమిషాల్లో బయలుదేరండి`, leaveNow:'మీరు ఇప్పుడు బయలుదేరవచ్చు', arrivalDesc:'కేంద్రం ఆలస్యంగా ఉంటే చాలా ముందుగా రావద్దు.', health:'కేంద్ర స్థితి', operational:'పనిలో ఉంది', paused:'నిలిపివేయబడింది', counters:(a,t)=>`${a}/${t} కౌంటర్లు యాక్టివ్`, model:'క్యూ మోడల్', perFarmer:n=>`${n} నిమి/రైతు`, modelDesc:'ప్రతి టోకెన్ పూర్తయ్యాక ETA మళ్లీ లెక్కించబడుతుంది.', journey:'కొనుగోలు ప్రయాణం', steps:['స్లాట్ నిర్ధారితం','కేంద్రానికి చేరారు','లైవ్ క్యూ','నాణ్యత తనిఖీ','తూకం','కొనుగోలు పూర్తి','చెల్లింపు ప్రారంభం'], progress:'ప్రగతిలో', operator:'ఆపరేటర్ డెమో', operatorDesc:'జడ్జీల ముందు లైవ్ క్యూ మార్పును చూపడానికి ఈ నియంత్రణలను వాడండి.', next:'తదుపరి రైతును పిలవండి', breakdown:'బ్రేక్‌డౌన్ చూపించండి', resume:'కేంద్రాన్ని తిరిగి ప్రారంభించండి', healthy:'సిస్టమ్ సక్రమంగా ఉంది. క్యూ ముందుకు కదిలినప్పుడు ETA అప్‌డేట్ అవుతుంది.', pausedMsg:'క్యూ నిలిపివేయబడింది. ప్రభావిత రైతులకు SMS/app అలర్ట్ వస్తుంది.', nearby:'సమీప కేంద్ర లోడ్', nearbyDesc:'తక్కువ రద్దీ ఉన్న అర్హత కేంద్రాన్ని కిసాన్‌స్లాట్ సూచించగలదు.', balancing:'డైనమిక్ లోడ్ బ్యాలెన్సింగ్', centre:'కేంద్రం', queue:'క్యూ', estWait:'అంచనా వేచి', status:'స్థితి', action:'చర్య', suggest:'సూచించు', procurementCentre:'కొనుగోలు కేంద్రం', dashboard:'డాష్‌బోర్డ్' },
  kn: { title:'ಕಿಸಾನ್‌ಸ್ಲಾಟ್ ಲೈವ್ ಕಾರ್ಯಾಚರಣೆ', subtitle:'ಸ್ಲಾಟ್ ಬುಕ್ಕಿಂಗ್ ನಂತರ ಮಾರುಕಟ್ಟೆಯ ನೈಜ-ಸಮಯ ಸ್ಥಿತಿ', token:'ನಿಮ್ಮ ಲೈವ್ ಟೋಕನ್', serving:'ಈಗ ಸೇವೆ', ahead:'ಮುಂದಿರುವ ರೈತರು', wait:'ಅಂದಾಜು ನಿರೀಕ್ಷೆ', min:'ನಿಮಿಷ', traffic:'ಮಾರುಕಟ್ಟೆ ದಟ್ಟಣೆ', low:'ಕಡಿಮೆ ದಟ್ಟಣೆ', moderate:'ಮಧ್ಯಮ', high:'ಹೆಚ್ಚು ದಟ್ಟಣೆ', trafficDesc:'ಲೈವ್ ಸರದಿ ಮತ್ತು ಸಕ್ರಿಯ ಕೌಂಟರ್‌ಗಳ ಆಧಾರದಲ್ಲಿ.', arrival:'ಸ್ಮಾರ್ಟ್ ಆಗಮನ', leaveIn:n=>`ಸುಮಾರು ${n} ನಿಮಿಷಗಳಲ್ಲಿ ಹೊರಡಿ`, leaveNow:'ನೀವು ಈಗ ಹೊರಡಬಹುದು', arrivalDesc:'ಕೇಂದ್ರ ವಿಳಂಬವಾದರೆ ತುಂಬಾ ಬೇಗ ತಲುಪಬೇಡಿ.', health:'ಕೇಂದ್ರ ಸ್ಥಿತಿ', operational:'ಕಾರ್ಯನಿರ್ವಹಣೆ', paused:'ತಾತ್ಕಾಲಿಕ ನಿಲುಗಡೆ', counters:(a,t)=>`${a}/${t} ಕೌಂಟರ್ ಸಕ್ರಿಯ`, model:'ಸರದಿ ಮಾದರಿ', perFarmer:n=>`${n} ನಿಮಿಷ/ರೈತ`, modelDesc:'ಪ್ರತಿ ಟೋಕನ್ ಮುಗಿದಾಗ ETA ಮರು ಲೆಕ್ಕಿಸಲಾಗುತ್ತದೆ.', journey:'ಖರೀದಿ ಪ್ರಯಾಣ', steps:['ಸ್ಲಾಟ್ ದೃಢ','ಕೇಂದ್ರಕ್ಕೆ ಆಗಮನ','ಲೈವ್ ಸರದಿ','ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ','ತೂಕ','ಖರೀದಿ ಪೂರ್ಣ','ಪಾವತಿ ಆರಂಭ'], progress:'ಪ್ರಗತಿಯಲ್ಲಿ', operator:'ಆಪರೇಟರ್ ಡೆಮೊ', operatorDesc:'ನ್ಯಾಯಾಧೀಶರ ಮುಂದೆ ಲೈವ್ ಸರದಿ ಬದಲಾವಣೆ ತೋರಿಸಲು ಈ ನಿಯಂತ್ರಣಗಳನ್ನು ಬಳಸಿ.', next:'ಮುಂದಿನ ರೈತನನ್ನು ಕರೆ', breakdown:'ಬ್ರೇಕ್‌ಡೌನ್ ತೋರಿಸಿ', resume:'ಕೇಂದ್ರ ಮರು ಆರಂಭಿಸಿ', healthy:'ಸಿಸ್ಟಮ್ ಸರಿಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ. ಸರದಿ ಮುಂದಾದಾಗ ETA ನವೀಕರಿಸುತ್ತದೆ.', pausedMsg:'ಸರದಿ ನಿಲ್ಲಿಸಲಾಗಿದೆ. ರೈತರಿಗೆ SMS/app ಎಚ್ಚರಿಕೆ ಹೋಗುತ್ತದೆ.', nearby:'ಹತ್ತಿರದ ಕೇಂದ್ರ ಲೋಡ್', nearbyDesc:'ಕಡಿಮೆ ದಟ್ಟಣೆಯ ಅರ್ಹ ಕೇಂದ್ರವನ್ನು ಕಿಸಾನ್‌ಸ್ಲಾಟ್ ಸೂಚಿಸಬಹುದು.', balancing:'ಡೈನಮಿಕ್ ಲೋಡ್ ಬ್ಯಾಲೆನ್ಸಿಂಗ್', centre:'ಕೇಂದ್ರ', queue:'ಸರದಿ', estWait:'ಅಂದಾಜು ನಿರೀಕ್ಷೆ', status:'ಸ್ಥಿತಿ', action:'ಕ್ರಿಯೆ', suggest:'ಸೂಚಿಸಿ', procurementCentre:'ಖರೀದಿ ಕೇಂದ್ರ', dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್' },
  ml: { title:'കിസാൻസ്ലോട്ട് ലൈവ് ഓപ്പറേഷൻസ്', subtitle:'സ്ലോട്ട് ബുക്കിംഗിന് ശേഷം മണ്ടിയുടെ തത്സമയ സ്ഥിതി', token:'നിങ്ങളുടെ ലൈവ് ടോക്കൺ', serving:'ഇപ്പോൾ സേവനം', ahead:'മുന്നിലുള്ള കർഷകർ', wait:'കാത്തിരിപ്പ് സമയം', min:'മിനിറ്റ്', traffic:'മണ്ടി തിരക്ക്', low:'കുറഞ്ഞ തിരക്ക്', moderate:'മിതമായ', high:'കൂടിയ തിരക്ക്', trafficDesc:'ലൈവ് ക്യൂയും പ്രവർത്തിക്കുന്ന കൗണ്ടറുകളും അടിസ്ഥാനമാക്കി.', arrival:'സ്മാർട്ട് വരവ്', leaveIn:n=>`ഏകദേശം ${n} മിനിറ്റിൽ പുറപ്പെടുക`, leaveNow:'ഇപ്പോൾ പുറപ്പെടാം', arrivalDesc:'കേന്ദ്രം വൈകുകയാണെങ്കിൽ വളരെ നേരത്തെ എത്തേണ്ടതില്ല.', health:'കേന്ദ്ര സ്ഥിതി', operational:'പ്രവർത്തിക്കുന്നു', paused:'നിർത്തിയിരിക്കുന്നു', counters:(a,t)=>`${a}/${t} കൗണ്ടർ പ്രവർത്തിക്കുന്നു`, model:'ക്യൂ മോഡൽ', perFarmer:n=>`${n} മിനിറ്റ്/കർഷകൻ`, modelDesc:'ഓരോ ടോക്കനും പൂർത്തിയായാൽ ETA വീണ്ടും കണക്കാക്കും.', journey:'വാങ്ങൽ യാത്ര', steps:['സ്ലോട്ട് സ്ഥിരീകരിച്ചു','കേന്ദ്രത്തിലെത്തി','ലൈവ് ക്യൂ','ഗുണനിലവാര പരിശോധന','തൂക്കം','വാങ്ങൽ പൂർത്തിയായി','പേയ്മെന്റ് ആരംഭിച്ചു'], progress:'നടന്നുകൊണ്ടിരിക്കുന്നു', operator:'ഓപ്പറേറ്റർ ഡെമോ', operatorDesc:'ജഡ്ജിമാരുടെ മുന്നിൽ ലൈവ് ക്യൂ മാറുന്നത് കാണിക്കാൻ ഈ നിയന്ത്രണങ്ങൾ ഉപയോഗിക്കുക.', next:'അടുത്ത കർഷകനെ വിളിക്കുക', breakdown:'തകരാർ കാണിക്കുക', resume:'കേന്ദ്രം പുനരാരംഭിക്കുക', healthy:'സിസ്റ്റം സാധാരണ നിലയിലാണ്. ക്യൂ നീങ്ങുമ്പോൾ ETA പുതുക്കും.', pausedMsg:'ക്യൂ നിർത്തി. ബാധിത കർഷകർക്ക് SMS/app അറിയിപ്പ് ലഭിക്കും.', nearby:'സമീപ കേന്ദ്ര ലോഡ്', nearbyDesc:'കുറഞ്ഞ തിരക്കുള്ള യോഗ്യ കേന്ദ്രം കിസാൻസ്ലോട്ട് നിർദേശിക്കും.', balancing:'ഡൈനമിക് ലോഡ് ബാലൻസിംഗ്', centre:'കേന്ദ്രം', queue:'ക്യൂ', estWait:'കാത്തിരിപ്പ്', status:'സ്ഥിതി', action:'നടപടി', suggest:'നിർദേശം', procurementCentre:'വാങ്ങൽ കേന്ദ്രം', dashboard:'ഡാഷ്ബോർഡ്' },
  or: { title:'କିସାନସ୍ଲଟ୍ ଲାଇଭ୍ ଅପରେସନ୍', subtitle:'ସ୍ଲଟ୍ ବୁକିଂ ପରେ ମଣ୍ଡିର ଲାଇଭ୍ ସ୍ଥିତି', token:'ଆପଣଙ୍କ ଲାଇଭ୍ ଟୋକନ୍', serving:'ବର୍ତ୍ତମାନ ସେବା', ahead:'ଆଗରେ କୃଷକ', wait:'ଆନୁମାନିକ ଅପେକ୍ଷା', min:'ମିନିଟ୍', traffic:'ମଣ୍ଡି ଭିଡ଼', low:'କମ୍ ଭିଡ଼', moderate:'ମଧ୍ୟମ', high:'ଅଧିକ ଭିଡ଼', trafficDesc:'ଲାଇଭ୍ କ୍ୟୁ ଓ ସକ୍ରିୟ କାଉଣ୍ଟର ଆଧାରିତ।', arrival:'ସ୍ମାର୍ଟ ଆଗମନ', leaveIn:n=>`ପ୍ରାୟ ${n} ମିନିଟ୍ ପରେ ବାହାରନ୍ତୁ`, leaveNow:'ଆପଣ ଏବେ ବାହାରି ପାରିବେ', arrivalDesc:'କେନ୍ଦ୍ରରେ ବିଳମ୍ବ ହେଲେ ଅତି ଶୀଘ୍ର ଆସନ୍ତୁ ନାହିଁ।', health:'କେନ୍ଦ୍ର ସ୍ଥିତି', operational:'ଚାଲୁ', paused:'ବନ୍ଦ', counters:(a,t)=>`${a}/${t} କାଉଣ୍ଟର ସକ୍ରିୟ`, model:'କ୍ୟୁ ମଡେଲ୍', perFarmer:n=>`${n} ମିନିଟ୍/କୃଷକ`, modelDesc:'ପ୍ରତ୍ୟେକ ଟୋକନ୍ ଶେଷରେ ETA ପୁନଃ ଗଣନା ହୁଏ।', journey:'କ୍ରୟ ଯାତ୍ରା', steps:['ସ୍ଲଟ୍ ନିଶ୍ଚିତ','କେନ୍ଦ୍ରରେ ପହଞ୍ଚିଲେ','ଲାଇଭ୍ କ୍ୟୁ','ଗୁଣବତ୍ତା ଯାଞ୍ଚ','ଓଜନ','କ୍ରୟ ସମ୍ପୂର୍ଣ୍ଣ','ପେମେଣ୍ଟ ଆରମ୍ଭ'], progress:'ଚାଲିଛି', operator:'ଅପରେଟର ଡେମୋ', operatorDesc:'ଜଜଙ୍କ ସମ୍ମୁଖରେ ଲାଇଭ୍ କ୍ୟୁ ପରିବର୍ତ୍ତନ ଦେଖାନ୍ତୁ।', next:'ପରବର୍ତ୍ତୀ କୃଷକକୁ ଡାକନ୍ତୁ', breakdown:'ବିକଳ ଦେଖାନ୍ତୁ', resume:'କେନ୍ଦ୍ର ପୁନଃ ଚାଲୁ', healthy:'ସିଷ୍ଟମ୍ ସଠିକ୍ ଅଛି। କ୍ୟୁ ଆଗକୁ ବଢ଼ିଲେ ETA ଅପଡେଟ୍ ହୁଏ।', pausedMsg:'କ୍ୟୁ ବନ୍ଦ। କୃଷକମାନେ SMS/app ଆଲର୍ଟ ପାଇବେ।', nearby:'ନିକଟ କେନ୍ଦ୍ର ଭାର', nearbyDesc:'କମ୍ ଭିଡ଼ ଥିବା ଯୋଗ୍ୟ କେନ୍ଦ୍ର ସୁପାରିଶ କରାଯାଇପାରେ।', balancing:'ଡାଇନାମିକ୍ ଲୋଡ୍ ବ୍ୟାଲାନ୍ସିଂ', centre:'କେନ୍ଦ୍ର', queue:'କ୍ୟୁ', estWait:'ଅପେକ୍ଷା', status:'ସ୍ଥିତି', action:'କାର୍ଯ୍ୟ', suggest:'ସୁପାରିଶ', procurementCentre:'କ୍ରୟ କେନ୍ଦ୍ର', dashboard:'ଡ୍ୟାସବୋର୍ଡ' },
  as: { title:'কিষাণস্লট লাইভ অপাৰেচন', subtitle:'স্লট বুকিঙৰ পাছত মণ্ডীৰ লাইভ অৱস্থা', token:'আপোনাৰ লাইভ টোকেন', serving:'এতিয়া সেৱা', ahead:'আগৰ কৃষক', wait:'আনুমানিক অপেক্ষা', min:'মিনিট', traffic:'মণ্ডীৰ ভিৰ', low:'কম ভিৰ', moderate:'মধ্যম', high:'বেছি ভিৰ', trafficDesc:'লাইভ শাৰী আৰু সক্ৰিয় কাউণ্টাৰৰ ভিত্তিত।', arrival:'স্মাৰ্ট আগমন', leaveIn:n=>`প্ৰায় ${n} মিনিট পিছত ওলাওক`, leaveNow:'আপুনি এতিয়া ওলাব পাৰে', arrivalDesc:'কেন্দ্ৰ পলম হ’লে বেছি আগতে নাহিব।', health:'কেন্দ্ৰৰ অৱস্থা', operational:'চলমান', paused:'স্থগিত', counters:(a,t)=>`${a}/${t} কাউণ্টাৰ সক্ৰিয়`, model:'শাৰী মডেল', perFarmer:n=>`${n} মিনিট/কৃষক`, modelDesc:'প্ৰতিটো টোকেন শেষ হ’লে ETA পুনৰ গণনা হয়।', journey:'ক্ৰয় যাত্ৰা', steps:['স্লট নিশ্চিত','কেন্দ্ৰত উপস্থিত','লাইভ শাৰী','গুণমান পৰীক্ষা','ওজন','ক্ৰয় সম্পূৰ্ণ','পেমেণ্ট আৰম্ভ'], progress:'চলি আছে', operator:'অপাৰেটৰ ডেমো', operatorDesc:'বিচাৰকৰ সন্মুখত লাইভ শাৰীৰ পৰিবৰ্তন দেখুৱাবলৈ ব্যৱহাৰ কৰক।', next:'পৰৱৰ্তী কৃষকক মাতক', breakdown:'বিকল দেখুৱাওক', resume:'কেন্দ্ৰ পুনৰ আৰম্ভ', healthy:'ছিষ্টেম ঠিক আছে। শাৰী আগবাঢ়িলে ETA আপডেট হয়।', pausedMsg:'শাৰী বন্ধ। কৃষকলৈ SMS/app সতৰ্কতা যাব।', nearby:'ওচৰৰ কেন্দ্ৰৰ চাপ', nearbyDesc:'কম ভিৰ থকা যোগ্য কেন্দ্ৰ পৰামৰ্শ কৰিব পাৰে।', balancing:'ডাইনামিক লোড বেলেঞ্চিং', centre:'কেন্দ্ৰ', queue:'শাৰী', estWait:'অপেক্ষা', status:'অৱস্থা', action:'কাৰ্য', suggest:'পৰামৰ্শ', procurementCentre:'ক্ৰয় কেন্দ্ৰ', dashboard:'ডেশ্বব’ৰ্ড' },
};

// Remaining listed languages use Hindi script/content fallback so the UI never falls back to English.
['ur','sa','ks','sd','kok','doi','mni','ne'].forEach(code => { if (!COPY[code]) COPY[code] = COPY.hi; });

export default function Operations() {
  const navigate = useNavigate();
  const { language } = useLanguage();
  const t = COPY[language] || COPY.hi;
  const [centers, setCenters] = useState(centerSeed);
  const [myToken] = useState(118);
  const [serving, setServing] = useState(111);
  const selected = centers[0];
  const farmersAhead = Math.max(myToken - serving - 1, 0);
  const eta = farmersAhead * selected.avg;
  const recommendedLeave = eta > 30 ? t.leaveIn(Math.max(eta - 20, 10)) : t.leaveNow;
  const traffic = useMemo(() => eta <= 30 ? { label:t.low, icon:'🟢' } : eta <= 60 ? { label:t.moderate, icon:'🟡' } : { label:t.high, icon:'🔴' }, [eta, t]);
  const advanceQueue = () => setServing(v => Math.min(v + 1, myToken));
  const togglePause = () => setCenters(prev => prev.map((c,i) => i === 0 ? { ...c, status:c.status === 'paused' ? 'operational' : 'paused' } : c));
  const card = { background:'#fff', border:'1px solid #e8ece8', borderRadius:18, padding:22, boxShadow:'0 10px 25px rgba(27,77,46,.07)' };
  const small = { fontSize:13, color:'#6b7b72', marginBottom:6 };
  const value = { fontSize:28, fontWeight:800, color:'#1B4D2E' };
  const centerName = c => `${c.location} ${t.procurementCentre}`;
  const statusText = c => c.status === 'paused' ? t.paused : c.status === 'high' ? t.high : t.operational;

  return <div style={{ minHeight:'100vh', background:'#f7faf7', fontFamily:'Segoe UI, sans-serif', color:'#24352c' }}>
    <div style={{ background:'#1B4D2E', color:'white', padding:'18px 5%', display:'flex', justifyContent:'space-between', alignItems:'center', gap:15, flexWrap:'wrap' }}>
      <div><div style={{ fontSize:24, fontWeight:900 }}>{t.title}</div><div style={{ opacity:.8, fontSize:13 }}>{t.subtitle}</div></div>
      <button onClick={()=>navigate('/dashboard')} style={{ border:0, borderRadius:10, padding:'10px 16px', fontWeight:700, cursor:'pointer' }}>← {t.dashboard}</button>
    </div>
    <main style={{ width:'90%', maxWidth:1180, margin:'28px auto 60px' }}>
      <section style={{ ...card, background:'linear-gradient(135deg,#1B4D2E,#2D7A3E)', color:'white', marginBottom:22 }}>
        <div style={{ display:'flex', justifyContent:'space-between', gap:20, flexWrap:'wrap', alignItems:'center' }}>
          <div><div style={{ fontSize:13, opacity:.8 }}>{t.token}</div><div style={{ fontSize:48, fontWeight:900 }}>KS-{myToken}</div><div style={{ marginTop:8 }}>{centerName(selected)}</div></div>
          <div style={{ display:'grid', gridTemplateColumns:'repeat(3,minmax(120px,1fr))', gap:12 }}>
            <div style={{ background:'rgba(255,255,255,.12)', padding:14, borderRadius:12 }}><div style={{ fontSize:12, opacity:.8 }}>{t.serving}</div><b style={{ fontSize:24 }}>KS-{serving}</b></div>
            <div style={{ background:'rgba(255,255,255,.12)', padding:14, borderRadius:12 }}><div style={{ fontSize:12, opacity:.8 }}>{t.ahead}</div><b style={{ fontSize:24 }}>{farmersAhead}</b></div>
            <div style={{ background:'rgba(255,255,255,.12)', padding:14, borderRadius:12 }}><div style={{ fontSize:12, opacity:.8 }}>{t.wait}</div><b style={{ fontSize:24 }}>{eta} {t.min}</b></div>
          </div>
        </div>
      </section>
      <section style={{ display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))', gap:16, marginBottom:22 }}>
        <div style={card}><div style={small}>{t.traffic}</div><div style={value}>{traffic.icon} {traffic.label}</div><div style={{ marginTop:8, color:'#6b7b72' }}>{t.trafficDesc}</div></div>
        <div style={card}><div style={small}>{t.arrival}</div><div style={{ ...value, fontSize:22 }}>{recommendedLeave}</div><div style={{ marginTop:8, color:'#6b7b72' }}>{t.arrivalDesc}</div></div>
        <div style={card}><div style={small}>{t.health}</div><div style={{ ...value, fontSize:22 }}>{selected.status === 'paused' ? '⏸️' : '✅'} {statusText(selected)}</div><div style={{ marginTop:8, color:'#6b7b72' }}>{t.counters(selected.active, selected.total)}</div></div>
        <div style={card}><div style={small}>{t.model}</div><div style={{ ...value, fontSize:22 }}>{t.perFarmer(selected.avg)}</div><div style={{ marginTop:8, color:'#6b7b72' }}>{t.modelDesc}</div></div>
      </section>
      <section style={{ display:'grid', gridTemplateColumns:'1.3fr .7fr', gap:18, marginBottom:22 }}>
        <div style={card}><h2 style={{ marginTop:0, color:'#1B4D2E' }}>{t.journey}</h2>{t.steps.map((step,i)=><div key={step} style={{ display:'flex', gap:12, alignItems:'center', padding:'11px 0', borderBottom:i<6?'1px solid #edf0ed':'none' }}><div style={{ width:28,height:28,borderRadius:'50%',display:'grid',placeItems:'center',fontWeight:800,background:i<2?'#dff3e4':i===2?'#fff1c7':'#eef1ee',color:'#1B4D2E' }}>{i<2?'✓':i+1}</div><div style={{ fontWeight:i===2?800:600 }}>{step}</div>{i===2&&<span style={{ marginLeft:'auto',color:'#b7791f',fontSize:13 }}>{t.progress}</span>}</div>)}</div>
        <div style={card}><h2 style={{ marginTop:0,color:'#1B4D2E' }}>{t.operator}</h2><p style={{ color:'#6b7b72',lineHeight:1.5 }}>{t.operatorDesc}</p><button onClick={advanceQueue} style={{ width:'100%',padding:12,border:0,borderRadius:10,background:'#1B4D2E',color:'white',fontWeight:800,cursor:'pointer',marginBottom:10 }}>{t.next}</button><button onClick={togglePause} style={{ width:'100%',padding:12,borderRadius:10,background:'#fff',border:'1px solid #d8ded9',fontWeight:800,cursor:'pointer' }}>{selected.status==='paused'?t.resume:t.breakdown}</button><div style={{ marginTop:16,padding:12,borderRadius:10,background:selected.status==='paused'?'#fff3e8':'#f2f8f3',fontSize:13 }}>{selected.status==='paused'?`⚠️ ${t.pausedMsg}`:t.healthy}</div></div>
      </section>
      <section style={card}><div style={{ display:'flex',justifyContent:'space-between',gap:15,flexWrap:'wrap',alignItems:'end' }}><div><h2 style={{ margin:0,color:'#1B4D2E' }}>{t.nearby}</h2><p style={{ color:'#6b7b72' }}>{t.nearbyDesc}</p></div><span style={{ fontSize:12,background:'#eef6ef',color:'#1B4D2E',padding:'7px 10px',borderRadius:20,fontWeight:700 }}>{t.balancing}</span></div><div style={{ overflowX:'auto' }}><table style={{ width:'100%',borderCollapse:'collapse',marginTop:12 }}><thead><tr style={{ textAlign:'left',color:'#6b7b72' }}><th style={{ padding:10 }}>{t.centre}</th><th>{t.queue}</th><th>{t.estWait}</th><th>{t.status}</th><th>{t.action}</th></tr></thead><tbody>{centers.map(c=>{const wait=Math.ceil((c.queue*c.avg)/Math.max(c.active,1));return <tr key={c.id} style={{ borderTop:'1px solid #edf0ed' }}><td style={{ padding:12,fontWeight:700 }}>{centerName(c)}</td><td>{c.queue}</td><td>{wait} {t.min}</td><td>{statusText(c)}</td><td>{c.id===3?<button style={{ border:0,background:'#F4D03F',color:'#1B4D2E',padding:'7px 10px',borderRadius:8,fontWeight:800,cursor:'pointer' }}>{t.suggest}</button>:'—'}</td></tr>})}</tbody></table></div></section>
    </main>
  </div>;
}
